config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/home', to: 'home#index'
  get '/contact', to: 'home#contact'

  get '/provinces', to: 'home#provinces'
  get '/provinces/:code/districts', to: 'home#districts'
  get '/districts/:code/wards', to: 'home#wards'

  devise_for :users

  resources :admin_users do
    collection do
      get :execute_users
      get :download_csv
      get :download_csv_score_board
      get :download_csv_elective_subject
    end
  end

  patch '/admin_users/:id/update_user_contact', to: 'admin_users#update_user_contact', as: 'update_admin_user_contact'
  patch '/admin_users/:id/update_relationship', to: 'admin_users#update_relationship', as: 'update_admin_user_relationship'

  get '/import_student', to: 'admin_users#import_student', as: 'import_student'
  get '/student_sample', to: 'admin_users#student_sample', as: 'student_sample'
  post '/update_import_student', to: 'admin_users#update_import_student', as: 'update_import_student'
  get '/import_student_class', to: 'admin_users#import_student_class', as: 'import_student_class'
  post '/update_import_student_class', to: 'admin_users#update_import_student_class', as: 'update_import_student_class'
  get '/student_classes_sample', to: 'admin_users#student_classes_sample', as: 'student_classes_sample'
  get '/students_sample', to: 'admin_users#students_sample', as: 'students_sample'
  post '/delete_student', to: 'admin_users#delete_student', as: 'delete_student'


  get '/admin_users/:id/edit_secondary_school_user', to: 'admin_users#edit_secondary_school_user', as: 'edit_admin_user_secondary_school_user'
  patch '/admin_users/:id/update_secondary_school_user', to: 'admin_users#update_secondary_school_user', as: 'update_admin_users_secondary_school_user'


  resources :basic_informations do
    collection do
      patch 'update_password', to: 'basic_informations#update_password', as: 'update_password'
      get 'edit_password', to: 'basic_informations#edit_password', as: 'edit_password'
    end
  end

  get '/basic_informations/:id/edit_user_contact', to: 'basic_informations#edit_user_contact', as: 'edit_user_contact'
  patch '/basic_informations/:id/update_user_contact', to: 'basic_informations#update_user_contact', as: 'update_user_contact'
  get '/basic_informations/:id/edit_relationship', to: 'basic_informations#edit_relationship', as: 'edit_relationship'
  patch '/basic_informations/:id/update_relationship', to: 'basic_informations#update_relationship', as: 'update_relationship'

  get '/basic_informations/:id/edit_secondary_school_user', to: 'basic_informations#edit_secondary_school_user', as: 'edit_secondary_school_user'
  patch '/basic_informations/:id/update_secondary_school_user', to: 'basic_informations#update_secondary_school_user', as: 'update_secondary_school_user'

  resources :user_contacts
  resources :student_classes
  resources :relationships

  resources :settings do
    collection do
      post 'update_setting', to: 'settings#update_setting', as: 'update_admin'
    end
  end


  resources :forms do
    collection do
      get 'profile_file/:id', to: 'forms#profile_file', as: 'profile_file'
      get 'commitment_file/:id', to: 'forms#commitment_file', as: 'commitment_file'
      get 'score_board_file/:id', to: 'forms#score_board_file', as: 'score_board_file'
    end
  end

  resources :elective_subjects, :only => [:index, :create]
end

app/views/base/_breadcrumbs.html.erb
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
                    <h1 class="m-0 text-dark"><%= @title_page %></h1>
    </div>
    <div class="col-sm-6">
      <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item">
          <%= link_to 'Trang chủ', root_path, class: "breadcrumb-item #{!defined?(breadcrumbs) ? 'active' : nil}" %>
        </li>

        <% if (defined?(breadcrumbs) && !breadcrumbs.nil? && breadcrumbs.size > 0)  %>
          <% breadcrumbs.each do |breadcrumb| %>
            <li class="breadcrumb-item <%= breadcrumbs.last == breadcrumb ? 'active' : nil %>">
              <% if (breadcrumbs.last != breadcrumb) %>
                <%= link_to breadcrumb[0], breadcrumb[1] %>
              <% else %>
                <%= breadcrumb[0] %>
              <% end %>
            </li>
          <% end %>
        <% end %>

      </ol>
    </div>
  </div>
</div>

app/views/base/_control_sidebar.html.erb
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Control sidebar content goes here -->
  <div class="p-3">
    <h5>Title</h5>
    <p>Sidebar content</p>
  </div>
</aside>
<!-- /.control-sidebar -->

app/views/base/_footer.html.erb
<!-- Main Footer -->
<footer class="main-footer">
  <!-- To the right -->
  <div class="float-right d-none d-sm-inline">
<!--    Anything you want-->
  </div>
  <!-- Default to the left -->
  <strong>
<!--    Copyright &copy; 2014-2019 <a >AdminLTE.io</a>.-->
  </strong>
<!--  All rights reserved.-->
</footer>

app/views/base/_header.html.erb
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to 'Trang chủ', home_path, :class => "nav-link #{current_class?(home_path)}" %>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to 'Liên hệ', contact_path, :class => "nav-link #{current_class?(contact_path)}" %>
    </li>
  </ul>

  <!-- SEARCH FORM -->
<!--  <form class="form-inline ml-3">-->
<!--    <div class="input-group input-group-sm">-->
<!--      <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">-->
<!--      <div class="input-group-append">-->
<!--        <button class="btn btn-navbar" type="submit">-->
<!--          <i class="fas fa-search"></i>-->
<!--        </button>-->
<!--      </div>-->
<!--    </div>-->
<!--  </form>-->

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#" aria-expanded="false">
        <i class="far fa-user"></i>
        <%= current_user.email %>
        <span class="badge badge-info navbar-badge">*</span>
      </a>
      <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right" style="left: inherit; right: 0px;">
<!--        <span class="dropdown-item dropdown-header">15 Notifications</span>-->
        <div class="dropdown-divider"></div>
        <%= form_for(:user, url: destroy_user_session_path, :method => :delete) do |f| %>
          <button type="submit" name="commit" class="dropdown-item">
            <i class="fas fa-sign-out-alt"></i>
            <%= "Đăng xuất" %>
          </button>
        <% end %>
        <div class="dropdown-divider"></div>
        <a href="<%= edit_password_basic_informations_path %>" class="dropdown-item">
          <i class="fas fa-exchange-alt"></i>
          <%= "Đổi mật khẩu" %>
        </a>
        <div class="dropdown-divider"></div>
<!--        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>-->
      </div>
    </li>
  </ul>
</nav>
<!-- /.navbar -->

app/views/base/_sidebar.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
    <%= link_to home_path, class: "brand-link" do %>
    <%= image_tag ("/assets/BHHLogo.jpeg"), class: "brand-image img-circle elevation-3", alt: "BHH Logo", style: "opacity: .8" %>
      <span class="brand-text font-weight-light">THPT Bình Hưng Hoà</span>
    <% end %>
<!--    <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"-->
<!--         style="opacity: .8">-->

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
<!--    <div class="user-panel mt-3 pb-3 mb-3 d-flex">-->
<!--      <div class="image">-->
        <%#= image_tag("/assets/avatar.png") %>
<!--      </div>-->
<!--      <div class="info text-center">-->
<!--        <a href="#">-->
          <%#= current_user.email %>
<!--        </a>-->
        <%#= form_for(:user, url: destroy_user_session_path, :method => :delete) do |f| %>
          <%#= f.submit "Log out",  class: "btn btn-danger btn-xs text-center" %>
        <%# end %>
<!--      </div>-->
<!--    </div>-->

    <!-- Sidebar Menu -->

    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <% if (current_user.role == 5) %>
          <li class="nav-item <%= menu_open_class?([])%> ">
            <%= link_to admin_users_path, :class => "nav-link  #{current_class?(admin_users_path)}" do %>
              <i class="fa fa-tasks nav-icon"></i>
              <p>
                <%= 'Quản lý người dùng' %>
              </p>
            <% end %>
          </li>
        <% end %>

        <li class="nav-item <%= menu_open_class?([])%> ">
          <%= link_to basic_informations_url, :class => "nav-link  #{current_class?(basic_informations_path)}" do %>
            <i class="fa fa-user-alt nav-icon"></i>
            <p>
              <%= 'Thông tin cá nhân' %>
            </p>
          <% end %>
        </li>


        <li class="nav-item <%= menu_open_class?([])%> ">
          <%= link_to forms_path, :class => "nav-link  #{current_class?(forms_path)}" do %>
            <i class="fa fa-file nav-icon"></i>
            <p>
              <%= 'Các biểu mẫu' %>
            </p>
          <% end %>
        </li>

        <% if (current_user.role == 5) %>
          <li class="nav-item <%= menu_open_class?([])%> ">
            <%= link_to settings_path, :class => "nav-link  #{current_class?(settings_path)}" do %>
              <i class="fa fa-cog nav-icon"></i>
              <p>
                <%= 'Cài đặt' %>
              </p>
            <% end %>
          </li>
        <% end %>

        <%# if (current_user.role == 0 || current_user.role == 5 ) %>
          <li class="nav-item <%= menu_open_class?([])%> ">
            <%= link_to elective_subjects_path, :class => "nav-link  #{current_class?(elective_subjects_path)}" do %>
              <i class="fa fa-file-alt nav-icon"></i>
              <p>
                <%= 'ĐK Môn học tự chọn' %>
              </p>
            <% end %>
          </li>
        <%# end %>

      </ul>
    </nav>

    <!-- /.sidebar-menu -->

  </div>
  <!-- /.sidebar -->
</aside>