config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/home', to: 'home#index'
  get '/contact', to: 'home#contact'

  get '/provinces', to: 'home#provinces'
  get '/provinces/:code/districts', to: 'home#districts'
  get '/districts/:code/wards', to: 'home#wards'

  devise_for :users

  resources :admin_users do
    collection do
      get :execute_users
      get :download_csv
      get :download_csv_score_board
      get :download_csv_elective_subject
    end
  end

  patch '/admin_users/:id/update_user_contact', to: 'admin_users#update_user_contact', as: 'update_admin_user_contact'
  patch '/admin_users/:id/update_relationship', to: 'admin_users#update_relationship', as: 'update_admin_user_relationship'

  get '/import_student', to: 'admin_users#import_student', as: 'import_student'
  get '/student_sample', to: 'admin_users#student_sample', as: 'student_sample'
  post '/update_import_student', to: 'admin_users#update_import_student', as: 'update_import_student'
  get '/import_student_class', to: 'admin_users#import_student_class', as: 'import_student_class'
  post '/update_import_student_class', to: 'admin_users#update_import_student_class', as: 'update_import_student_class'
  get '/student_classes_sample', to: 'admin_users#student_classes_sample', as: 'student_classes_sample'
  get '/students_sample', to: 'admin_users#students_sample', as: 'students_sample'
  post '/delete_student', to: 'admin_users#delete_student', as: 'delete_student'


  get '/admin_users/:id/edit_secondary_school_user', to: 'admin_users#edit_secondary_school_user', as: 'edit_admin_user_secondary_school_user'
  patch '/admin_users/:id/update_secondary_school_user', to: 'admin_users#update_secondary_school_user', as: 'update_admin_users_secondary_school_user'


  resources :basic_informations do
    collection do
      patch 'update_password', to: 'basic_informations#update_password', as: 'update_password'
      get 'edit_password', to: 'basic_informations#edit_password', as: 'edit_password'
    end
  end

  get '/basic_informations/:id/edit_user_contact', to: 'basic_informations#edit_user_contact', as: 'edit_user_contact'
  patch '/basic_informations/:id/update_user_contact', to: 'basic_informations#update_user_contact', as: 'update_user_contact'
  get '/basic_informations/:id/edit_relationship', to: 'basic_informations#edit_relationship', as: 'edit_relationship'
  patch '/basic_informations/:id/update_relationship', to: 'basic_informations#update_relationship', as: 'update_relationship'

  get '/basic_informations/:id/edit_secondary_school_user', to: 'basic_informations#edit_secondary_school_user', as: 'edit_secondary_school_user'
  patch '/basic_informations/:id/update_secondary_school_user', to: 'basic_informations#update_secondary_school_user', as: 'update_secondary_school_user'

  resources :user_contacts
  resources :student_classes
  resources :relationships

  resources :settings do
    collection do
      post 'update_setting', to: 'settings#update_setting', as: 'update_admin'
    end
  end


  resources :forms do
    collection do
      get 'profile_file/:id', to: 'forms#profile_file', as: 'profile_file'
      get 'commitment_file/:id', to: 'forms#commitment_file', as: 'commitment_file'
      get 'score_board_file/:id', to: 'forms#score_board_file', as: 'score_board_file'
    end
  end

  resources :elective_subjects, :only => [:index, :create]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper
  before_action :is_signed_in?

  def index
  end

  def contact
  end

  def provinces
    provinces = Province.all
    render json: provinces
  end

  def districts
    province = Province.where(:code => params[:code]).first()
    districts = District.where(:parent_code => province.code).order(:code)
    render json: districts
  end

  def wards
    district = District.where(:code => params[:code]).first()
    wards = Ward.where(:parent_code => district.code).order(:code)
    render json: wards
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<!-- Main content -->
    <!-- Default box -->
<div class="content pt-5">

  <div class="card bg-light d-flex flex-fill">
    <div class="card-header text-muted border-bottom-0">
      Quản trị viên
    </div>
    <div class="card-body pt-10">
      <div class="row">
        <div class="col-6 pt-10 text-right">
          <h2 class="lead"><b>Thầy: Kiều Trí Hoà</b></h2>
          <p class="text-muted text-sm"><b>Chuyên viên tư vấn học đường</b>  </p>
          <ul class="ml-4 mb-0 fa-ul text-muted">
<!--            <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>-->
            <li class="medium text-right">
              <i class="fas fa-lg fa-phone"></i>
              <a href="tel:0983818987">
                Phone #: 0983818987
              </a>
            </li>
          </ul>
        </div>
        <div class="col-6 text-left">
          <img src="/assets/avatar.png" alt="user-avatar" class="img-circle img-fluid">
        </div>
      </div>
    </div>
    <div class="card-footer">
    </div>
  </div>
</div>

app/views/home/index.html.erb
<section class="content">
  <div class="container-fluid">
    <!-- Small boxes (Stat box) -->

    <div class="row">
      <div class="col-md-12">
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>Xin chào <%= current_user.full_name %>!</strong> Thông báo cập nhật mới!
          <%= link_to "Cập nhật kết quả học tập lớp 9", edit_secondary_school_user_path(current_user.id), class: "btn btn-warning"%>
          <%= link_to "Cập nhật thông tin cá nhân", edit_basic_information_path(current_user.id), class: "btn btn-warning"%>
          <%= link_to "Cập nhật thông tin gia đình", edit_relationship_path(current_user.id), class: "btn btn-primary"%>

          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
      <div class="col-md-12">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="<%= image_path("/assets/img.png") %>" alt="First slide">
              <div class="carousel-caption d-none d-md-block text-primary">
                <h5 class="text-primary">THPT Bình Hưng Hoà</h5>
                <p class="text-dark">Xin chào <%= current_user.full_name %>!</p>
              </div>
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="<%= image_path("/assets/img_2.png") %>" alt="Second slide">
              <div class="carousel-caption d-none d-md-block">
                <h5 class="text-primary">THPT Bình Hưng Hoà</h5>
                <p class="text-primary">Lễ khai giảng</p>
              </div>
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="<%= image_path("/assets/img_1.png") %>" alt="Third slide">
              <div class="carousel-caption d-none d-md-block">
                <h5 class="text-primary">THPT Bình Hưng Hoà</h5>
                <p class="text-primary">Hoạt động ngoại khoá</p>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>

    <!-- /.row -->
    <!-- Main row -->
    <!-- /.row (main row) -->
  </div><!-- /.container-fluid -->
</section>