config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/home', to: 'home#index'
  get '/contact', to: 'home#contact'

  get '/provinces', to: 'home#provinces'
  get '/provinces/:code/districts', to: 'home#districts'
  get '/districts/:code/wards', to: 'home#wards'

  devise_for :users

  resources :admin_users do
    collection do
      get :execute_users
      get :download_csv
      get :download_csv_score_board
      get :download_csv_elective_subject
    end
  end

  patch '/admin_users/:id/update_user_contact', to: 'admin_users#update_user_contact', as: 'update_admin_user_contact'
  patch '/admin_users/:id/update_relationship', to: 'admin_users#update_relationship', as: 'update_admin_user_relationship'

  get '/import_student', to: 'admin_users#import_student', as: 'import_student'
  get '/student_sample', to: 'admin_users#student_sample', as: 'student_sample'
  post '/update_import_student', to: 'admin_users#update_import_student', as: 'update_import_student'
  get '/import_student_class', to: 'admin_users#import_student_class', as: 'import_student_class'
  post '/update_import_student_class', to: 'admin_users#update_import_student_class', as: 'update_import_student_class'
  get '/student_classes_sample', to: 'admin_users#student_classes_sample', as: 'student_classes_sample'
  get '/students_sample', to: 'admin_users#students_sample', as: 'students_sample'
  post '/delete_student', to: 'admin_users#delete_student', as: 'delete_student'


  get '/admin_users/:id/edit_secondary_school_user', to: 'admin_users#edit_secondary_school_user', as: 'edit_admin_user_secondary_school_user'
  patch '/admin_users/:id/update_secondary_school_user', to: 'admin_users#update_secondary_school_user', as: 'update_admin_users_secondary_school_user'


  resources :basic_informations do
    collection do
      patch 'update_password', to: 'basic_informations#update_password', as: 'update_password'
      get 'edit_password', to: 'basic_informations#edit_password', as: 'edit_password'
    end
  end

  get '/basic_informations/:id/edit_user_contact', to: 'basic_informations#edit_user_contact', as: 'edit_user_contact'
  patch '/basic_informations/:id/update_user_contact', to: 'basic_informations#update_user_contact', as: 'update_user_contact'
  get '/basic_informations/:id/edit_relationship', to: 'basic_informations#edit_relationship', as: 'edit_relationship'
  patch '/basic_informations/:id/update_relationship', to: 'basic_informations#update_relationship', as: 'update_relationship'

  get '/basic_informations/:id/edit_secondary_school_user', to: 'basic_informations#edit_secondary_school_user', as: 'edit_secondary_school_user'
  patch '/basic_informations/:id/update_secondary_school_user', to: 'basic_informations#update_secondary_school_user', as: 'update_secondary_school_user'

  resources :user_contacts
  resources :student_classes
  resources :relationships

  resources :settings do
    collection do
      post 'update_setting', to: 'settings#update_setting', as: 'update_admin'
    end
  end


  resources :forms do
    collection do
      get 'profile_file/:id', to: 'forms#profile_file', as: 'profile_file'
      get 'commitment_file/:id', to: 'forms#commitment_file', as: 'commitment_file'
      get 'score_board_file/:id', to: 'forms#score_board_file', as: 'score_board_file'
    end
  end

  resources :elective_subjects, :only => [:index, :create]
end

app/controllers/admin_users_controller.rb
require 'app_utils'
require 'excel_utils'

class AdminUsersController < ApplicationController
  include ApplicationHelper
  before_action :is_signed_in?
  before_action :is_admin?
  rescue_from ActiveRecord::InvalidForeignKey, with: :invalid_foreign_key

  def index

    @users = User.all
    @title_page = 'Danh Sách Tài khoản'
    @breadcrumbs = [
      ['Danh Sách Tài khoản', admin_users_path],
    ]
  end

  def show
    @user = User.find(params[:id])
    @province = Province.where(code: @user.province).first()
    @user_contact = UserContact.where(:user_id => params[:id]).first()
    @student_classess = StudentClass.where(:user_id => @user.id)
    @relationship = Relationship.where(:user_id =>  params[:id]).first()
    @secondary_school_user = SecondarySchoolUser.where(user_id: @user.id).first()
    elective_subject_data = ElectiveSubject.where(user_id: @user.id).first()
    if !elective_subject_data.nil?
      @elective_subject = {
        :name => current_user[:name],
        :group_subject => GROUP_SUBJECT.select{|g| g[:code] == elective_subject_data.group_subject}.first[:name],
        :thematic_group => THEMATIC_GROUP.select{|g| g[:code] == elective_subject_data.thematic_group}.first[:name],
        :elective_subject_one => ELECTIVE_SUBJECT_ONE.select{|g| g[:code] == elective_subject_data.elective_subject_one}.first[:name],
        :elective_subject_two => ELECTIVE_SUBJECT_TWO.select{|g| g[:code] == elective_subject_data.elective_subject_two}.first[:name],
        :alternative_subject => elective_subject_data.alternative_subject.present? ? ALTERNATIVE_SUBJECT.select{|g| g[:code] == elective_subject_data.alternative_subject}.first[:name] : nil,
      }
    end

    @title_page = @user.name
    @breadcrumbs = [
      ['Danh Sách Tài khoản', admin_users_path],
      [@user.name, admin_user_path(@user.id)]
    ]
  end

  def import_student
  end

  def update_import_student

    # files có thể ở dạng files hoặc là path của files đều được xử lý chính xác bởi method open
    # puts params[:files]
    spreadsheet = Roo::Spreadsheet.open params[:file]
    # lấy cột header (column name)
    header = spreadsheet.row 1
    (2..spreadsheet.last_row).each do |i|
      # lấy ra bản ghi và biến đổi thành hash để có thể tạo record tương ứng
      # row = [header, spreadsheet.row(i)].transpose.to_h
      row = spreadsheet.row(i)
      if (row[1].nil? || row[2].nil? || row[3].nil?)
      else
        password = row[4].nil? ? '123456' : row[4]
        name = row[1].to_s.split(' ').last
        User.create(:full_name => row[1], :name => name, :email => row[2], :student_code => row[3], :password => password)
        # @user = User.where(:student_code =>  row[3]).first();
        # @student_class = StudentClass.where(:user_id => @user.id).first_or_create(:user_id => @user.id);
        # @student_class.update(:class_name => row[5], :grade => row[6], :student_class_code => row[7])
        # redirect_to admin_users_path

      end
    end
    redirect_to admin_users_path
  end

  def import_student_class
  end

  def update_import_student_class

    # files có thể ở dạng files hoặc là path của files đều được xử lý chính xác bởi method open
    # puts params[:files]
    spreadsheet = Roo::Spreadsheet.open params[:file]
    # lấy cột header (column name)
    header = spreadsheet.row 1
    (2..spreadsheet.last_row).each do |i|
      # lấy ra bản ghi và biến đổi thành hash để có thể tạo record tương ứng
      # row = [header, spreadsheet.row(i)].transpose.to_h
      row = spreadsheet.row(i)
      puts row[1]
      if !(row[1].nil?)
        @user = User.where(:student_code => row[1]).first()
        puts @user.nil?
        unless @user.nil?
          @student_class = StudentClass.create(:user_id => @user.id, :class_name => row[2], :grade => row[3], :student_class_code => row[4], :year => row[5])
        end
      end
    end
    redirect_to admin_users_path
  end
  
  def students_sample
    send_file Rails.root.join('app/assets/files/students.csv'), type: 'csv'
  end

  def student_classes_sample
    send_file Rails.root.join('app/assets/files/classes.csv'), type: 'csv'
  end

  def edit
    @user = User.find(params[:id])
    @provinces = Province.all
    @ethnicities = Ethnicity.all

    @relatioship = Relationship.where(:user_id => params[:id]).first()
    @user_contact = UserContact.where(:user_id => params[:id]).first()

    @household_districts = District.where(:parent_code => @user_contact.household_province).order(:code)
    @household_wards = Ward.where(:parent_code => @user_contact.household_district).order(:code)

    @contact_districts = District.where(:parent_code => @user_contact.contact_province).order(:code)
    @contact_wards = Ward.where(:parent_code => @user_contact.contact_district).order(:code)
    @user_classes = StudentClass.where(:user_id => @user.id).order(created_at: :desc)
    @student_class = StudentClass.new

    @religions = [['Không', 0], ['Công Giáo', 1],['Phật Giáo', 2], ['Hòa Hảo', 3],['Tin Lành', 4], ['Hồi Giáo', 5], ['Khác', 6]]
    @identification_types = [['Chưa có CCCD/CMND', 0], ['Đã có CMND', 1],['Đã có CCCD thường', 2], ['Đã có CCCD gắn chíp', 3]]

    @title_page = @user.name
    @breadcrumbs = [
      ['Danh Sách Tài Khoản', admin_users_path],
      [@user.name, edit_admin_user_path(@user.id)]
    ]
  end

  def update_user_contact
    @user = User.find(params[:id])
    @user_contact = UserContact.where(user_id: params[:id]).first()
    if @user_contact.update(edit_user_contact_params)
      redirect_to  edit_admin_user_path(params[:id])
    else
      @user = User.find(params[:id])
      @provinces = Province.all
      @ethnicities = Ethnicity.all

      @relatioship = Relationship.where(:user_id => params[:id]).first()
      @user_contact = UserContact.where(:user_id => params[:id]).first()

      @household_districts = District.where(:parent_code => @user_contact.household_province).order(:code)
      @household_wards = Ward.where(:parent_code => @user_contact.household_district).order(:code)

      @contact_districts = District.where(:parent_code => @user_contact.contact_province).order(:code)
      @contact_wards = Ward.where(:parent_code => @user_contact.contact_district).order(:code)
      @user_classes = StudentClass.where(:user_id => @user.id).order(created_at: :desc)
      @student_class = StudentClass.new

      @religions = [['Không', 0], ['Công Giáo', 1],['Phật Giáo', 2], ['Hòa Hảo', 3],['Tin Lành', 4], ['Hồi Giáo', 5], ['Khác', 6]]

      @title_page = @user.name
      @breadcrumbs = [
        ['Danh Sách Tài Khoản', admin_users_path],
        [@user.name, edit_admin_user_path(@user.id)]
      ]
      render :edit, status: :unprocessable_entity
    end
  end

  def update_relationship
    @user = User.find(params[:id])
    @relatioship = Relationship.where(user_id: params[:id]).first()
    if @relatioship.update(edit_relationship_params)
      redirect_to  edit_admin_user_path(params[:id])
    else
      @user = User.find(params[:id])
      @provinces = Province.all
      @ethnicities = Ethnicity.all

      @relatioship = Relationship.where(:user_id => params[:id]).first()
      @user_contact = UserContact.where(:user_id => params[:id]).first()

      @household_districts = District.where(:parent_code => @user_contact.household_province).order(:code)
      @household_wards = Ward.where(:parent_code => @user_contact.household_district).order(:code)

      @contact_districts = District.where(:parent_code => @user_contact.contact_province).order(:code)
      @contact_wards = Ward.where(:parent_code => @user_contact.contact_district).order(:code)
      @user_classes = StudentClass.where(:user_id => @user.id).order(created_at: :desc)
      @student_class = StudentClass.new

      @religions = [['Không', 0], ['Công Giáo', 1],['Phật Giáo', 2], ['Hòa Hảo', 3],['Tin Lành', 4], ['Hồi Giáo', 5], ['Khác', 6]]

      @title_page = @user.name
      @breadcrumbs = [
        ['Danh Sách Tài Khoản', admin_users_path],
        [@user.name, edit_admin_user_path(@user.id)]
      ]
      render :edit, status: :unprocessable_entity
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(edit_user_params)
      redirect_to  edit_admin_user_path(params[:id])
    else
      @provinces = Province.all
      @ethnicities = Ethnicity.all
      @religions = [['Không', 0], ['Công Giáo', 1],['Phật Giáo', 2], ['Hòa Hảo', 3],['Tin Lành', 4], ['Hồi Giáo', 5], ['Khác', 6]]

      render :edit, status: :unprocessable_entity
    end
  end

  def delete_student
    begin 
      rs = {succeed: false, data: {}}
      search = AppUtils.escape_search_query(params[:search])
      search = AppUtils.quote_string(search)
      user_ids = params[:user_ids].split(',')
      user_ids = user_ids.reject(&:blank?) if user_ids.present? && user_ids.kind_of?(Array)
      users = User.left_joins(:student_class).where.not(:role => 4)
      users = users.where("student_code ILIKE '%#{search}%' OR student_classes.class_name ILIKE '%#{search}%' OR full_name ILIKE '%#{search}%' OR email ILIKE '%#{search}%'") if search.present?
      users = users.where(:id => user_ids) if user_ids.present?
      delete_user_ids = users.pluck('users.id')

      ActiveRecord::Base.transaction do
        StudentClass.where(:user_id =>  delete_user_ids).delete_all
        UserContact.where(:user_id =>  delete_user_ids).delete_all
        Relationship.where(:user_id =>  delete_user_ids).delete_all
        User.where(:id => delete_user_ids).delete_all
      end

      rs[:succeed] = true
      return render json: rs
    rescue Exception => ex
      Rails.logger.info(ex.message)
      return render json: {
        :succeed => false,
        :data => nil,
        :message => ex.message
      }
    end
  end

  def destroy
    @user_contact = UserContact.where(:user_id =>  params[:id]).first()
    @user_contact.delete unless @user_contact.nil?
    @student_class = StudentClass.where(:user_id =>  params[:id]).delete_all

app/views/admin_users/_form_class.html.erb
    <%= form_for(@student_class, :url =>  student_classes_path) do |f| %>

      <div class="row">
        <div class="col-md-12">
          <table class="table table-bordered" id="table_users">
            <thead>
            <tr>
              <th style="width: 10px">#</th>
              <th>
                <%= 'Lớp' %>
              </th>
              <th>
                <%= 'Khối' %>
              </th>
              <th>
                <%= 'Mã số' %>
              </th>
              <th>
                <%= 'Năm' %>
              </th>
              <th>
                <%= 'Thao tác' %>
              </th>
            </tr>
            </thead>
            <tbody>
            <% @user_classes.each_with_index do |user_class, index| %>
              <tr>
                <td>
                  <%= index + 1 %>
                </td>
                <td>
                  <%= user_class.class_name %>
                </td>
                <td>
                  <%= user_class.grade %>
                </td>
                <td>
                  <%= user_class.student_class_code %>
                </td>
                <td>
                  <%= user_class.year %>
                </td>
                <td class="text-center">
                    <%= link_to student_class_path(user_class.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm"  do %>
                      <i class="fas fa-trash"></i>
                    <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>


          <div class="card card-default">
            <div class="card-header">
              <h3 class="card-title">
                <%= 'Thêm lớp mới' %>
              </h3>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <div class="form-group">
                    <label for="class_name">
                      <%= 'Lớp' %>
                    </label>
                    <%= f.hidden_field :user_id, id: "user_id", class: "form-control", value: @user.id %>
                    <%= f.text_field :class_name, id: "class_name", class: "form-control", placeholder: 'Tên lớp' %>
                    <% @student_class.errors.full_messages_for(:class_name).each do |message| %>
                      <div class="text-danger"><%= message %></div>
                    <% end %>
                  </div>
                </div>
                <div class="col-sm-3">
                  <div class="form-group">
                    <label for="class_name">
                      <%= 'Khối' %>
                    </label>

                    <%= f.text_field :grade, id: "grade", class: "form-control", placeholder: 'Tên khối' %>
                    <% @student_class.errors.full_messages_for(:grade).each do |message| %>
                      <div class="text-danger"><%= message %></div>
                    <% end %>
                  </div>
                </div>
                <div class="col-sm-3">
                  <div class="form-group">
                    <label for="class_name">
                      <%= 'Mã số' %>
                    </label>

                    <%= f.text_field :student_class_code, id: "student_class_code", class: "form-control", placeholder: 'Tên mã số' %>
                    <% @student_class.errors.full_messages_for(:student_class_code).each do |message| %>
                      <div class="text-danger"><%= message %></div>
                    <% end %>
                  </div>
                </div>
                <div class="col-sm-3">
                  <div class="form-group">
                    <label for="class_name">
                      <%= 'Năm học' %>
                    </label>
                    <%= f.text_field :year, id: "year", class: "form-control", placeholder: 'Năm học' %>
                    <% @student_class.errors.full_messages_for(:year).each do |message| %>
                      <div class="text-danger"><%= message %></div>
                    <% end %>
                  </div>
                </div>

              </div>
            </div>

            <div class="card-footer text-center">
              <button type="submit" class="btn btn-primary">
                <%= 'Thêm mới' %>
              </button>
              <%= link_to 'Huỷ', admin_users_path, class: "btn btn-danger"%>
            </div>
          </div>

        </div>
      </div>

    <% end %>

<%#= javascript_pack_tag 'edit_user_contact' %>

<script type="text/javascript">
</script>

app/views/admin_users/import_student.html.erb
<div class="content container-fluid">
  <div class="container-fluid">
    <div class="row">
      <!-- left column -->
      <div class="col-md-12">
        <!-- general form elements -->
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">
              Nhập danh sách học sinh
            </h3>
          </div>

          <div class="card-body">
            <div class="row">
<!--              <div class="col-sm-6">-->
<!--                <div class="form-group">-->
<!--                  <label for="exampleInputFile">File input</label>-->
<!--                  <div class="input-group">-->
<!--                    <div class="custom-files">-->
<!--                      <input type="files" class="custom-files-input" id="exampleInputFile">-->
<!--                      <label class="custom-files-label" for="exampleInputFile">Choose files</label>-->
<!--                    </div>-->
<!--                    <div class="input-group-append">-->
<!--                      <span class="input-group-text">Upload</span>-->
<!--                    </div>-->
<!--                  </div>-->
<!--                </div>-->
<!--              </div>-->
              <div class="col-sm-4">
              <%= link_to 'Excel mẫu', 'https://docs.google.com/spreadsheets/d/1BxTrJG3Zln_3Zs5nhVbDYlyc6ikrJwvdVgqjdqVQoGg/edit?usp=sharing', target: "_blank", class: "btn btn-info"%>
              </div>

              <div class="col-sm-8">
                <div class="form-group">
                  <form action="<%= update_import_student_path %>" method="post" enctype="multipart/form-data">
                    <%= csrf_meta_tags %>
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                    Select csv to upload:
                    <input type="file" name="file" id="file">
                    <input type="submit" value="Tải lên" name="submit">
                  </form>
                </div>


              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin_users/import_student_class.html.erb
<div class="content container-fluid">
  <div class="container-fluid">
    <div class="row">
      <!-- left column -->
      <div class="col-md-12">
        <!-- general form elements -->
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">
              Cập nhật thông tin lớp của học sinh
            </h3>
          </div>

          <div class="card-body">
            <div class="row">
<!--              <div class="col-sm-6">-->
<!--                <div class="form-group">-->
<!--                  <label for="exampleInputFile">File input</label>-->
<!--                  <div class="input-group">-->
<!--                    <div class="custom-files">-->
<!--                      <input type="files" class="custom-files-input" id="exampleInputFile">-->
<!--                      <label class="custom-files-label" for="exampleInputFile">Choose files</label>-->
<!--                    </div>-->
<!--                    <div class="input-group-append">-->
<!--                      <span class="input-group-text">Upload</span>-->
<!--                    </div>-->
<!--                  </div>-->
<!--                </div>-->
<!--              </div>-->
              <div class="col-sm-4">
              <%= link_to 'Excel mẫu', 'https://docs.google.com/spreadsheets/d/1J7cHfMWnLQiSV4sZqaDHVHwsUzAH5cnLPqgVVvknYg4/edit?usp=sharing', target: "_blank", class: "btn btn-info"%>
              </div>

              <div class="col-sm-8">
                <div class="form-group">
                  <form action="<%= update_import_student_class_path %>" method="post" enctype="multipart/form-data">
                    <%= csrf_meta_tags %>
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                    Select csv to upload:
                    <input type="file" name="file" id="file">
                    <input type="submit" value="Tải lên" name="submit">
                  </form>
                </div>


              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin_users/index.html.erb
<div class="content container-fluid" ng-controller="AdminUsersCtrl">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
              <%= 'Danh sách người dùng' %>
            </h3>
            <div class="card-tools">
              <% if current_user.role == 5 %>

            <form>

                <button 
                  type="button" 
                  class="btn btn-danger" 
                  ng-click="delete_student()" 
                  ng-class="{'disabled': !is_check_all && !user_ids}"
                  data-confirm="Are you sure?" 
                  rel="nofollow"
                  data-method="delete"
                >
                  <%= 'Xoá HS đã chọn' %>
                </button>
                <%= link_to 'Nhập Lớp học Excel', import_student_class_path, class: "btn btn-info"%>
                <%= link_to 'Nhập Tài khoản Excel', import_student_path, class: "btn btn-warning"%>

              </form>
                <% end %>
              <%#= link_to 'Tạo tài khoản', new_admin_user_path, class: "btn btn-primary"%>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div class="row">
              <div class="col-md-8">
                <div class="row">
                  <div class="input-group col-md-8">
                    <input class="form-control" name="search" ng-model="search" placeholder="Tìm kiếm" ng-keyup="$event.keyCode == 13 && search && getData()">
                    <div class="input-group-append">
                      <button class="btn btn-outline-secondary" type="button" ng-click="getData()"><i class="fa fa-search"></i></button>
                    </div>
                  </div>

                </div>
              </div>
              <h5 class="col-md-4 text-right">
                <span> Kích thước: 
                  <select class="form-control w-auto d-inline" ng-model="page_size" ng-change="getData()">
                    <option value="10">10</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                  </select>
                </span>
              </h5>
              <div class="row">
                <div class="col-auto m-2">
                  <form class="row" action="<%= download_csv_admin_users_path %>" method="get">
                    <input value={{search}} name="search" class="d-none">
                    <input value={{user_ids}} name="user_ids" class="d-none">
                    <button class="btn btn btn-success" type="submit">
                      <i class="fas fa-download mr-1"></i>
                      CSV
                    </button>
                  </form>
                </div>
                <div class="col-auto m-2">
                  <form class="row" action="<%= download_csv_score_board_admin_users_path %>" method="get">
                    <input value={{search}} name="search" class="d-none">
                    <input value={{user_ids}} name="user_ids" class="d-none">
                    <button class="btn btn btn-primary" type="submit">
                      <i class="fas fa-download mr-1"></i>
                      Xuất Bảng điểm
                    </button>
                  </form>
                </div>
                <div class="col-auto m-2">
                  <form class="row" action="<%= download_csv_elective_subject_admin_users_path %>" method="get">
                    <input value={{search}} name="search" class="d-none">
                    <input value={{user_ids}} name="user_ids" class="d-none">
                    <button class="btn btn btn-info" type="submit">
                      <i class="fas fa-download mr-1"></i>
                      Xuất Đk Môn học tự chọn
                    </button>
                  </form>
                </div>
              </div>
            </div>
            <div class="table-responsive">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th style="width: 50px" class="text-center">
                      <div class="icheck-success d-inline">
                        <input type="checkbox" name="check_all" id="check_all" ng-model="is_check_all" ng-change="check_all()">
                        <label for="check_all"></label>
                      </div>
                    </th>
                    <th style="width: 10px">#</th>
                    <th> Mã học sinh</th>
                    <th>Lớp</th>
                    <th>Họ và tên</th>
                    <th>Tên</th>
                    <th>Email</th>
                    <th>Thao tác</th>
                  </tr>
                </thead>
                <tbody ng-if="data.length > 0">
                  <tr ng-repeat="user in data track by $index">
                    <td class="text-center">
                      <div class="form-group clearfix" ng-if="user.student_code">
                        <div class="icheck-success d-inline">
                          <input type="checkbox" name="check_box_{{$index}}" id="checkboxUser_{{user.id}}" value="{{user.id}}" ng-model="user.check" ng-change="check_user()">
                          <label for="checkboxUser_{{user.student_code}}"></label>
                        </div>
                      </div>
                    </td>
                    <td>{{$index + 1 + page*page_size - page_size}}</td>
                    <td>{{user.student_code}}</td>
                    <td>{{user.last_class_name}}</td>
                    <td>{{user.full_name}}</td>
                    <td>{{user.name}}</td>
                    <td>{{user.email}}</td>
                    <td class="text-left" width="132px">
                      <a href="/admin_users/{{user.id}}" class="btn btn-info btn-sm" target="_blank"><i class="fas fa-eye"></i></a>
                      <% if current_user.role == 5 %>

                      <a href="/admin_users/{{user.id}}/edit" class="btn btn-warning btn-sm" target="_blank"><i class="fas fa-edit"></i></a>
                        <a ng-if="user.role != 4"
                          data-confirm="Are you sure?"
                          href="/admin_users/{{user.id}}"
                          class="btn btn-danger btn-sm"
                          rel="nofollow"
                          data-method="delete"
                        >
                          <i class="fas fa-trash"></i>
                        </a>
                        <% end %>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <nav aria-label="Page navigation example">
              <ul class="pagination">
                <li class="page-item" ng-click="previous()" ng-class="{'disabled': page == 1}">
                  <a class="page-link" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                  </a>
                </li>
                <li class="page-item" ng-repeat="p in [].constructor(total_pages) track by $index" ng-if="[0, 1, 2, page - 2, page - 1, page, page + 1, page + 2, total_pages - 3, total_pages - 2,  total_pages - 1].indexOf($index) !== -1" ng-class="{'active': $index + 1 == page}" ng-click="change_page($index + 1)">
                  <a class="page-link">{{$index + 1}}</a>
                </li>
                <li class="page-item" ng-click="next()" ng-class="{'disabled': page == total_pages}">
                  <a class="page-link" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /.card -->

      </div>
    </div>

  </div>
</div>
<script>
    $(function () {
        var globalScope = angular.element($('body')).scope();
        var ctrl = '[ng-controller=AdminUsersCtrl]';
        WebApp.AngularUtils.applyData(ctrl, 'init', function (scope) {
          scope.data = [];
          scope.execute_users_admin_users_path = '<%= execute_users_admin_users_path %>'
          scope.delete_student_path = '<%= delete_student_path %>'
          scope.getData();
        });
    });
</script>